---
name: Trigger tuatmcc.com deploy

on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions: {}

jobs:
  trigger-remote-deploy:
    name: Dispatch deploy.yml in tuatmcc/tuatmcc.com
    runs-on: ubuntu-latest
    if: github.repository != 'tuatmcc/tuatmcc.com'
    steps:
      - name: Trigger remote workflow_dispatch
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TUATMCC_WORKFLOW_TOKEN }}
          script: |
            try {
              await github.rest.actions.createWorkflowDispatch({
                owner: 'tuatmcc',
                repo: 'tuatmcc.com',
                workflow_id: 'deploy.yml',
                ref: 'main',
                inputs: {
                  source_repo: context.repo.repo,
                  source_owner: context.repo.owner,
                  source_sha: context.sha
                }
              });
              core.info('Dispatch sent to tuatmcc/tuatmcc.com deploy.yml');
            } catch (error) {
              core.setFailed(`Failed to dispatch: ${error.message}`);
            }

