---
name: Trigger tuatmcc.com deploy

on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions: {}

jobs:
  trigger-remote-deploy:
    name: Dispatch deploy.yml in tuatmcc/tuatmcc.com
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch tuatmcc.com build workflow
        env:
          GH_TOKEN: ${{ github.token }}
          OWNER: tuatmcc
          REPO: tuatmcc.com
          WF: deploy.yml
          REF: main
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${OWNER}/${REPO}/actions/workflows/${WF}/dispatches \
             -f ${REF}
